server:
  port: 9000

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/menudb
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: menu
    password: menu

mybatis:
  mapper-locations: mapper/*.xml